# Generated by Django 6.0.3 on 2026-03-07 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='edited',
            field=models.BooleanField(default=False),
        ),
    ]
